function yax = logpdf(obj, xax)

    % LOGPDF    log probability density function
    zax = ((xax(1,:) - obj.Mean(1)) / sqrt(obj.Covariance(1,1)))^2 ...
          - 2 * obj.Correlation ...
          * ((xax(1,:) - obj.Mean(1)) / sqrt(obj.Covariance(1,1))) ...
          * ((xax(2,:) - obj.Mean(2)) / sqrt(obj.Covariance(2,2))) ...
          + ((xax(2,:) - obj.Mean(2)) / sqrt(obj.Covariance(2,2)))^2;
    yax = pi * sqrt(obj.Covariance(1,1)) * sqrt(obj.Covariance(2,2)) ...
          * (1 - obj.Correlation^2)^(-0.5) * zax;
end