function yax = pdf(obj, xax)

    % PDF    Probability density function
    zax = ((xax(1,:) - obj.Mean(1)) / sqrt(obj.Covariance(1,1))).^2 ...
          + (((xax(1,:) - obj.Mean(1)) / sqrt(obj.Covariance(1,1))) ...
          .* ((xax(2,:) - obj.Mean(2)) / sqrt(obj.Covariance(2,2))) ...
          .* (-2 * obj.Correlation)) ...
          + ((xax(2,:) - obj.Mean(2)) / sqrt(obj.Covariance(2,2))).^2;
    yax = obj.ScalingConstant ...
          * (sqrt(obj.Covariance(1,1)) * sqrt(obj.Covariance(2,2)))^(-1) ...
          * sqrt(1 - obj.Correlation^2)^(-1) ...
          * exp(-0.5 * zax * (1 - obj.Correlation^2)^(-1));
end